name: 'Execute a script on seperated ubuntu environment'
description: 'execute a script on prepared ubuntu environment'
inputs:
  script:
    description: 'Relative path of script to execute.'
    required: true
  on:
    description: 'Codename of ubuntu version, e.g. focal, jammy'
    required: true
outputs: {}
runs:
  using: 'docker'
  image: "Dockerfile"

branding:
  icon: 'box'
  color: 'green'